Feature/jc 598 make a book catalog page with a new design
saritasa-nest/camp-js-2024-ky-tran pull request #1
Opened 2024-07-04 08:14 UTC by kytran-saritasa

Hi everyone,

I have deployed my code on Netlify for easier access and review. Please check the links below:

Website: https://6686581d581ff59e8e7175e4--saritasa-book-catalog.netlify.app/
Figma Design: https://www.figma.com/design/oM3DYfGGZ7Kck8jvchh3XJ/JS-Camp?node-id=13-262&t=OvTKsmxtxJdAIlLa-0

Please don’t hesitate to give comments and advice, as they will help me become a better builder. Thank you all so much.

Best regards,
Ky Tran

2024-07-04 17:34 UTC, LocTran-saritasa requested changes
1. Let's remove some obvious comments in your HTML and CSS files. I understand your purpose but we often use comments to note just in some specific scenario. Ex to tell why you use `!important` or why you want to disable an Eslint rule, ...
2. About the web preview, let's take a look at your book's image size, it's depending on the viewport width, but in the design, it's fixed regardless the viewport's width is changed
3. Could you customize your checkbox to match the one in the design?

2024-07-04 17:34 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/styles/index.css
> +}
Great to have separate classes for each font style 👍 
You should define all of them in another file `typography.css` in the global directory for better reuse

2024-07-04 17:34 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/styles/index.css
> +/* Layout styles */
Let's remove all comments in `index.css`, we can understand the meaning of a class through its name

2024-07-04 17:34 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/styles/index.css
> +  width: 14px;
Avoid hardcoded size if possible
https://wiki.saritasa.rocks/frontend/languages/css#dont-set-hardcoded-size

2024-07-04 17:34 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/styles/index.css
> +  display: block;
Not sure why we must use these ID selectors. Is it possible to use classes? As discussed in lecture, ID selector is bad practice

2024-07-04 17:34 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/styles/index-responsive.css
> +*/
Great research 🚀 
But please simplify it, just leave the link and one explanation line is enough

2024-07-04 17:34 UTC, LocTran-saritasa commented on apps/vanilla/src/global/variables.css
> +  --shadow-color-small: #0000001a;
I don't quite understand what's the meaning of number `0.1` 🤔

2024-07-04 17:42 UTC, SofyaKirillova requested changes
Please, delete the example folder

2024-07-04 17:42 UTC, SofyaKirillova commented on apps/vanilla/src/global/variables.css
> +  --width-tiny-layout-number: 380;
`number` doesn't make sense here

2024-07-04 17:42 UTC, SofyaKirillova commented on apps/vanilla/src/pages/styles/index.css
Let's move all the styles to a separate file, and leave only the imports here

2024-07-04 17:42 UTC, SofyaKirillova commented on apps/vanilla/src/pages/styles/index.css
> +  line-height: 1.6;
Let's use one style to write the `line-height` value
In other places you use `px`

2024-07-04 17:42 UTC, SofyaKirillova commented on apps/vanilla/src/pages/styles/index-responsive.css
> +    flex: calc(var(--gap-large-number) / var(--width-main-layout-number));
If you use `flex-grow`, let's write it that way

2024-07-04 17:42 UTC, SofyaKirillova commented on apps/vanilla/src/pages/styles/index-responsive.css
> +  #sort,
It is better to use classes instead of ids

2024-07-04 17:42 UTC, SofyaKirillova commented on apps/vanilla/src/pages/styles/index.css
> +  padding-left: 48px;
Let's put `48px` in a separate variable.
By creating a variable, we will put the necessary meaning in the name and we will not need to leave a comment

2024-07-04 17:42 UTC, SofyaKirillova commented on apps/vanilla/src/pages/styles/index.css
> +  /* stylelint-disable-next-line property-no-vendor-prefix */
When disabling the rules, you need to add a comment describing why we did this

2024-07-04 17:42 UTC, SofyaKirillova commented on apps/vanilla/src/pages/styles/index.css
> +  height: 128px;
We have a `--height-main-footer` variable for this

2024-07-04 17:42 UTC, SofyaKirillova commented on apps/vanilla/src/pages/index.html
![image](https://github.com/saritasa-nest/camp-js-2024-ky-tran/assets/108254953/2c7854e1-8c69-4863-be46-d2d07ac80214)
There is a space between the border and the edge

2024-07-04 17:42 UTC, SofyaKirillova commented on apps/vanilla/src/pages/index.html
> +          <span class="main__footer-more-info-copyright">© 2023</span>
```suggestion
          <span class="main__footer-more-info-copyright">&copy; 2023</span>
```

2024-07-05 02:54 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/styles/index-responsive.css
> +*/
Well done for taking the trouble to write documentation for the module 🔥  It's just not very informative. Try to answer the question of how and why the user should use your code or solutions.

Let's take the MDN (or Angular. or React) documentation as an example.

2024-07-05 03:02 UTC, andrey-gazzaev commented on apps/vanilla/src/global/base.css
> +  outline: none;
If you decide to take away the user's ability to see the outline, you must give the user an alternative option. For example border by hover/active etc.

2024-07-05 07:16 UTC, kytran-saritasa commented on apps/vanilla/src/pages/index.html
> +            <span class="subtitle-font-semibold letter-spacing-tiny">YEAR</span>
In the design, the gap between 'YEAR' and '2020' is 8px, so I use display flex here to make it look like in the design, one line with word spacing is also good but sometimes it pretty hard to handle :3

2024-07-05 07:23 UTC, kytran-saritasa commented on apps/vanilla/src/pages/styles/index.css
> +/* Layout styles */
That's a very good idea brother and I delete all those comments in media queries, but I still keep some in the main one so other newbie like me can understand it easier

2024-07-05 07:27 UTC, kytran-saritasa commented on apps/vanilla/src/global/variables.css
> +  --shadow-color-small: #0000001a;
Sorry bro, I just get used to the way of using rgba like this rgba(0, 0, 0, 0.1). So 0.1 is just the number in rgba I comment for referencing while I am in the code process, then I forgot to delete. I just delete it now, thanks you so much for pointing that out

2024-07-05 07:27 UTC, kytran-saritasa commented on apps/vanilla/src/global/variables.css
> +  /* 0.05 */
Sorry bro, I just get used to the way of using rgba like this rgba(0, 0, 0, 0.1). So 0.1 is just the number in rgba I comment for referencing while I am in the code process, then I forgot to delete. I just delete it now, thanks you so much for pointing that out

2024-07-05 08:21 UTC, kytran-saritasa commented on apps/vanilla/src/pages/assets/images/logos/touchicon-android-192.jpeg
Thank you for pointing that out :3, I just would like to support multiple sizes based on this: [App Touch-icon](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html).
Now I only keep one version of the image 512 * 512 for all devices

2024-07-05 10:53 UTC, andrey-gazzaev requested changes
Good job 👍

2024-07-05 10:53 UTC, andrey-gazzaev commented on .vscode/settings.json
> +{
Let's add this file to gitignor

2024-07-05 10:53 UTC, andrey-gazzaev commented on apps/vanilla/src/global/base.css
> +	font-size: 62.5%;
If you want to reset the default font size, then use pixels.
The fact is that different browsers have different initial settings.

2024-07-05 10:53 UTC, andrey-gazzaev commented on apps/vanilla/src/global/button.css
> +button {
Since these are custom styles, let's use a class prefixed like `.camp-button`. This will allow us to easily extend custom styles. In addition, we do not mix default browser styles and ours.

2024-07-05 10:53 UTC, andrey-gazzaev commented on apps/vanilla/src/global/input.css
> +input {
same

2024-07-05 10:53 UTC, andrey-gazzaev commented on apps/vanilla/src/global/main.css
> +	display: none;
You hid the scroll, but what did you give the user in return? The user may be confused by the fact that he does not see the scroll. Let's style it better

2024-07-05 10:53 UTC, andrey-gazzaev commented on apps/vanilla/src/global/main.css
> +	top: -1px;
Why is `top: 0` not working properly?

2024-07-05 10:53 UTC, andrey-gazzaev commented on apps/vanilla/src/global/main.css
> +	flex: calc(var(--width-tiny-layout-no-unit) / var(--width-main-layout-no-unit));
Why not just use `flex:1` for content and `flex:0.5` for filters?
https://stackblitz.com/edit/js-zdfavb?file=index.js,index.html,style.css

2024-07-05 10:53 UTC, andrey-gazzaev commented on apps/vanilla/src/global/main.css
> +	/* Set height like this violates the Wiki best practices but this is for easier to calculate layout later */
```suggestion
```
If you have a fixed height, then there is nothing wrong with specifying it

2024-07-05 10:53 UTC, andrey-gazzaev commented on apps/vanilla/src/global/main.css
> +	/* Set height like this violates the Wiki best practices but this is for easier to calculate layout later */
same

2024-07-05 10:53 UTC, andrey-gazzaev commented on apps/vanilla/src/global/main.css
> +@media only screen and (max-width: 80em) {
```suggestion
@media only screen and (max-width: 1280px) {
```
Let's use pixels and leave the relative units to the fonts.

2024-07-05 10:53 UTC, andrey-gazzaev commented on apps/vanilla/src/global/variables.css
> +	--font-size-small: 1.6rem;
I suggest you add a base size which will be in pixels and set the default font size to html.

2024-07-05 10:53 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/index.html
> +			<div class="content-gap"></div>
As soon as you set the maximum page size and specify the ratio of the content part to the filters. Then you will not have problems with gap, since its size is taken into account in flex.

Let's use `gap: 24px`

2024-07-05 10:53 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/index.html
> +					<h1 class="logo-font-bold">Books app</h1>
There can only be one `h1` on a page

2024-07-05 11:42 UTC, daoduong-saritasa requested changes

2024-07-05 11:42 UTC, daoduong-saritasa commented on apps/vanilla/src/global/variables.css
> +	--heading-color-3: #b0e0e6;
Color with number naming doesn't have any meaning, please consider come up with better one

2024-07-05 11:42 UTC, daoduong-saritasa commented on apps/vanilla/src/global/variables.css
> +	--gap-huge: 80px;
```suggestion
	--gap-medium: 24px;
	--gap-large: 32px;
	--gap-extra-large: 40px;
	--gap-huge: 80px;
```

2024-07-05 11:42 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.html
> +
Please remove empty line

2024-07-05 11:42 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.html
> +		<header class="main__header">
Consider this
```suggestion
<body class="container">
	<main class="main">
		<header class="main__header">
```

2024-07-05 11:42 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.html
> +			<h1 class="logo-font-bold">📚 Books app</h1>
Header should has it's own font if a logo has one, as this is a header block and it contain a logo, so naming the font to `header-font-bold` would be more correct

2024-07-05 11:42 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.html
> +		<main class="content">
Try to use only one `main` per document. Review this https://arc.net/l/quote/wcdtswqf

2024-07-05 11:42 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.html
> +						<input id="search" class="body-font-regular search-control" name="search" type="text"
https://wiki.saritasa.rocks/frontend/languages/html#avoid-id

2024-07-05 11:42 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.html
> +						<select id="sort" class="body-font-regular sort-control" required>
Same with id

2024-07-05 11:42 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.html
> +
Remove empty line

2024-07-06 09:52 UTC, kytran-saritasa commented on apps/vanilla/src/pages/index.html
> +			<h1 class="logo-font-bold">📚 Books app</h1>
Thanks brother! The reason why I use 'logo-font-bold' here because we reuse it in the footer.
<img width="222" alt="Screenshot 2024-07-06 at 4 50 53 PM" src="https://github.com/saritasa-nest/camp-js-2024-ky-tran/assets/174303568/d805b88b-b412-450f-b56e-a71bca279ad4">

2024-07-06 09:59 UTC, kytran-saritasa commented on apps/vanilla/src/pages/index.html
> +						<input id="search" class="body-font-regular search-control" name="search" type="text"
Thanks brother! I use put ID here for future use I we add JS to the site, and now I style the page only using class.

2024-07-06 10:18 UTC, kytran-saritasa commented on apps/vanilla/src/global/main.css
> +@media only screen and (max-width: 80em) {
Thanks bro!
Please take a look at this [article](https://zellwk.com/blog/media-query-units/) able px, em and rem, px is not going to work well on Safari.

2024-07-06 10:29 UTC, kytran-saritasa commented on apps/vanilla/src/global/main.css
> +	display: none;
Please take a look at the [design](https://www.figma.com/design/oM3DYfGGZ7Kck8jvchh3XJ/JS-Camp?node-id=13-262&t=HIh4IIkvO8Pu0H8b-0). We only use scroll for books section but not the entire page.

2024-07-06 11:10 UTC, kytran-saritasa commented on apps/vanilla/src/global/main.css
> +	flex: calc(var(--width-tiny-layout-no-unit) / var(--width-main-layout-no-unit));
For the width of each one is like in the design, I new use grid to solve this problem and now it works well

2024-07-06 11:10 UTC, kytran-saritasa commented on apps/vanilla/src/global/main.css
> +	top: -1px;
When I use grid for the layout, now it works properly with `top: 0`

2024-07-06 11:12 UTC, kytran-saritasa commented on apps/vanilla/src/global/variables.css
> +	--font-size-small: 1.6rem;
I have sent you a DM, please check Slack

2024-07-06 11:13 UTC, kytran-saritasa commented on apps/vanilla/src/global/base.css
> +	font-size: 62.5%;
Please check DM on Slack, thank you

2024-07-06 14:24 UTC, SofyaKirillova requested changes
We have an artifact in the mobile version

![image](https://github.com/saritasa-nest/camp-js-2024-ky-tran/assets/108254953/820f28a9-cd97-48e5-a64b-d71dff6af58c)

2024-07-06 14:24 UTC, SofyaKirillova commented on apps/vanilla/src/global/main.css
> +	background: var(--shadow-color-tiny);
```suggestion
	background-color: var(--shadow-color-tiny);
```
Use `background-color`, `background-image` etc. This improves the readability of the code

2024-07-06 14:24 UTC, SofyaKirillova commented on apps/vanilla/src/global/main.css
> +	background: var(--shadow-color-tiny);
Same

2024-07-06 14:24 UTC, SofyaKirillova commented on apps/vanilla/src/global/main.css
> +/* 786px */
Please, improve the comment

2024-07-06 14:24 UTC, SofyaKirillova commented on apps/vanilla/src/global/main.css
> +/* 640px */
Same

2024-07-06 14:24 UTC, SofyaKirillova commented on apps/vanilla/src/global/typography.css
> +	line-height: 1.33;
Please, round it up

2024-07-06 14:24 UTC, SofyaKirillova commented on apps/vanilla/src/global/variables.css
> +	--main-text-color: #000;
https://wiki.saritasa.rocks/frontend/languages/css#naming

Let's improve the names

2024-07-06 14:24 UTC, SofyaKirillova commented on apps/vanilla/src/global/main.css
> +	flex: 1;
If you use flex-grow, let's write it that way

Also check in other places

2024-07-06 14:24 UTC, SofyaKirillova commented on apps/vanilla/src/pages/index.html
> +				<div class="content-gap"></div>
Does this class exist?

2024-07-06 15:21 UTC, kytran-saritasa commented on apps/react/src/api/index.ts
> +/** Http. */
Thank you! This is just a temporary comment I use to pass the Linting process (I don't know the reason why Linting now not only check for Vanilla but also for React and Angular) and I will fix later when it comes to the React part.

2024-07-06 15:23 UTC, kytran-saritasa commented on apps/vanilla/src/global/main.css
> +	top: -1px;
Please take a look at this [review](https://github.com/saritasa-nest/camp-js-2024-ky-tran/pull/1#pullrequestreview-2161534297)

2024-07-07 03:39 UTC, kytran-saritasa commented on apps/vanilla/src/global/main.css
> +	flex: 1;
flex-grow is not good for responsive, I see that using 'flex' is fine
<img width="639" alt="Screenshot 2024-07-07 at 10 38 33 AM" src="https://github.com/saritasa-nest/camp-js-2024-ky-tran/assets/174303568/1c631817-f6c4-4b82-ac45-80990cb6f045">

2024-07-07 03:43 UTC, kytran-saritasa commented on apps/vanilla/src/global/typography.css
> +	line-height: 1.33;
I use 1.33 here because it will make the line-height 24px which is like in the design. Wiki best practices is also ok with a number with 2 decimal numbers.
https://wiki.saritasa.rocks/frontend/languages/css#dont-be-too-precise

2024-07-08 03:16 UTC, andrey-gazzaev commented on apps/vanilla/src/global/main.css
> +@media only screen and (max-width: 80em) {
https://developer.mozilla.org/en-US/docs/Web/CSS/max-width#browser_compatibility
https://developer.mozilla.org/en-US/docs/Web/CSS/@media#specifications
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/width#browser_compatibility

Judging by the documentation: everything should work.

https://wiki.saritasa.rocks/frontend/languages/css#be-careful-with-font-related-units
In addition, we have a rule on WIKI for relative units of measurement

2024-07-08 03:36 UTC, SofyaKirillova commented on apps/vanilla/src/global/main.css
> +	flex: 1;
You also need to add `flex-basis: 0;`
![Снимок экрана от 2024-07-08 10-31-42](https://github.com/saritasa-nest/camp-js-2024-ky-tran/assets/108254953/8a2bec1e-b67c-47fb-8a12-aa2795bc2d0e)

2024-07-08 03:48 UTC, SofyaKirillova requested changes
Why do you have different `font-size`?

![image](https://github.com/saritasa-nest/camp-js-2024-ky-tran/assets/108254953/6b6d6aaf-1bcc-4e2c-adb1-243bc4907a07)
![image](https://github.com/saritasa-nest/camp-js-2024-ky-tran/assets/108254953/b7d3dbd0-f04c-4840-a7ad-b6284372298b)

2024-07-08 03:48 UTC, SofyaKirillova commented on apps/vanilla/src/global/main.css
> +	top: -1px;
Please briefly describe why you are using top: -1px.

2024-07-08 04:17 UTC, andrey-gazzaev reviewed
I found that your layout breaks down at sizes from 900px to 1050px
![image](https://github.com/saritasa-nest/camp-js-2024-ky-tran/assets/108252114/6259c9f0-c697-4624-9b9b-aa1b69a7b91d)
![image](https://github.com/saritasa-nest/camp-js-2024-ky-tran/assets/108252114/01fed018-ad52-4d9b-a379-2610a241bc02)
![image](https://github.com/saritasa-nest/camp-js-2024-ky-tran/assets/108252114/fcbfc0f1-e0ad-477d-a3a0-7f0f040cbfac)

2024-07-08 04:17 UTC, andrey-gazzaev commented on apps/vanilla/src/global/main.css
> +@media only screen and (max-width: 64em) {
Please stick to the pixel sizing approach. https://wiki.saritasa.rocks/frontend/languages/css#be-careful-with-font-related-units

2024-07-08 04:17 UTC, andrey-gazzaev commented on apps/vanilla/src/global/variables.css
> +	--text-color-main: #000;
```suggestion
	--background-color-main: #ffffff;
	--text-color-main: #000000;
```

2024-07-08 04:17 UTC, andrey-gazzaev commented on apps/vanilla/src/global/utils.css
> +}
Sorry, but I apparently did not express myself correctly. You can use tags to reset the default browser styles for the entire application. 

Then I said that if we add a reusable style, then we need to use a class with the prefix of your application) For example `camp-button` or `camp-input`

2024-07-08 04:17 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/index.html
> +					<a href="#" class="body-font-regular main__footer-more-github">Github</a>
Let's add a title to this link

2024-07-08 12:44 UTC, LocTran-saritasa commented on apps/vanilla/src/global/utils.css
> +}
Let's create `button.css` and `index.css` and put these styles into them.
I would suggest you an example for `button.css`. You can do the samething for `input.css`
```css
button.camp-button {
    // Your base button styles
}

button.camp-button_outlined {
    // Another button type. Add its additional styles here
}
```

```html
// Use common button
<button class="camp-button" type=...></button>
// Use outlined button
<button class="camp-button camp-button_outlined" type=...></button>
```

2024-07-08 14:31 UTC, kytran-saritasa commented on apps/vanilla/src/global/main.css
> +@media only screen and (max-width: 80em) {
Thanks bro! I am going to use px in media query from now

2024-07-08 14:59 UTC, kytran-saritasa commented on apps/vanilla/src/global/main.css
> +	top: -1px;
I still don't know the reason bro, sometimes it happens on my computer and sometimes it does not. But when I use `top: 0;` 2 days ago and SofyaKirillova saw [that weird UI](https://monosnap.com/file/s5zicpZP9JTnVKg0H1OSmViKnYKgR1) again. Now I just would like to play it safe here by using `top: -1px`. I will follow you best practice whenever I can.

2024-07-08 15:04 UTC, kytran-saritasa commented on apps/vanilla/src/global/variables.css
> +	--text-color-main: #000;
<img width="397" alt="Screenshot 2024-07-08 at 10 00 28 PM" src="https://github.com/saritasa-nest/camp-js-2024-ky-tran/assets/174303568/a89507af-5b3d-4696-98ee-482a5a3ab262">
The StyleLint requires the color short syntax with hex color and not use something like rgb

2024-07-08 15:06 UTC, andrey-gazzaev commented on apps/vanilla/src/global/variables.css
> +	--text-color-main: #000;
It is unexpected for me) Leave it as is

2024-07-08 15:07 UTC, andrey-gazzaev commented on apps/vanilla/src/global/main.css
> +	top: -1px;
Ok, since this is a floating bug, let's leave it at -1

2024-07-08 15:21 UTC, kytran-saritasa commented on apps/vanilla/src/global/main.css
> +	flex: 1;
Wow it works beautifully. I learn new thing today, thank you so much.

2024-07-08 15:22 UTC, kytran-saritasa commented on apps/vanilla/src/global/main.css
> +	width: 100%;
Done! I learn new thing to day that don't try to over complicate thing.

2024-07-08 15:28 UTC, kytran-saritasa commented on apps/vanilla/src/global/main.css
> +	padding: 20px 0;
Wow bro, this is the first time that I have seen padding-block. Learn new thing today

2024-07-09 05:37 UTC, LocTran-saritasa approved these changes

2024-07-09 05:37 UTC, LocTran-saritasa commented on apps/vanilla/src/global/button.css
> +button.primary-button__to-top {
`to-top` is sticking to a specific UI, imagine that you want to reuse this style for a button in another place, but this time, it's not used to go to the top. That's when the naming makes confusion
I suggest either moving this style to the `css` file or giving it a better name

2024-07-09 05:37 UTC, LocTran-saritasa commented on apps/vanilla/src/global/input.css
> +input.primary-input_search {
can we use `input[type="search"]`?

2024-07-09 05:39 UTC, LocTran-saritasa commented on apps/vanilla/src/global/button.css
> +button.primary-button__to-top {
`to-top` is sticking to a specific UI, imagine that you want to reuse this style for a button in another place, but this time, it's not used to go to the top. That's when the naming makes confusion
I suggest either moving this style to the css file or giving it a better name

2024-07-09 05:39 UTC, LocTran-saritasa commented on apps/vanilla/src/global/input.css
> +input.primary-input_search {
can we use `input[type="search"]`?

2024-07-09 06:25 UTC, SofyaKirillova approved these changes

2024-07-09 08:50 UTC, LocTran-saritasa approved these changes
Well done 🔥

2024-07-09 10:58 UTC, daoduong-saritasa approved these changes

2024-07-09 11:08 UTC, andrey-gazzaev approved these changes

2024-07-09 11:08 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/index.html
> +							<img class="category__book-image" src="/assets/images/books/image-9.png" alt="Book image">
```suggestion
							<img class="category__book-image" src="/assets/images/books/image-9.png" alt="Book image">
```
The `alt` attribute is used not only for alternative display of the image but also for description. 

For example, a user with visual impairments will only hear the text from the alt attribute.

Ideally, you should describe what is in the picture in this attribute. It will be enough for the user to understand that this is a book poster and recognize its title

2024-07-09 11:08 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/index.html
> +						<span class="main__footer-more-info-copyright">&copy; 2023</span>
```suggestion
						<span class="main__footer-more-info-copyright">&copy; 2024</span>
```

2024-07-10 02:34 UTC, kytran-saritasa commented on apps/vanilla/src/global/button.css
> +button.primary-button__text-icon {
Done! 💥💥💥

2024-07-10 02:53 UTC, merged