Feature: Blackjack by dice game JC-624
saritasa-nest/camp-js-2024-ky-tran pull request #3
Opened 2024-07-13 09:51 UTC by kytran-saritasa

Please don’t hesitate to give comments and advice, as they will help me become a better builder. Thank you all so much.

2024-07-16 10:10 UTC, andrey-gazzaev requested changes
![image](https://github.com/user-attachments/assets/4eab424d-4aab-4a6e-b9a3-0d322e8653a2)
It looks like your game is impossible to finish. 

Besides, I can't start the game again. What if I want to get even?

2024-07-16 10:10 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/black-jack/scripts/controllers/players.ts
> +	private readonly winStatus = new Publisher<WinStatus>();
It looks strange that the player himself checks the game results.

What if he cheats?

2024-07-16 10:10 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/black-jack/scripts/views/initial-displayers.ts
> +export class InitialAdminDisplayer implements Subscriber<null> {
Typically we separate entities into different files. They are simply easier to maintain

2024-07-16 10:10 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/black-jack/scripts/views/results-displayers.ts
> +export class ResultsAdminDisplayer extends ResultsDisplayer implements Subscriber<PlayerResults> {
same

2024-07-16 10:56 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/black-jack/scripts/config/index.ts
> +export const WINNER_DICE_TOTAL_RESULT = 21;
```suggestion
export const WIN_POINT = 21;
```

2024-07-16 10:56 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/black-jack/scripts/controllers/generators.ts
> +	 */
For this function we don't need `returns` docs, it's obvious that this function is returning a random number. Let's remove to not overloading our docs
```suggestion
	/** Simulates rolling a dice and returns the result. */
```

2024-07-17 03:05 UTC, kytran-saritasa commented on apps/vanilla/src/pages/black-jack/scripts/controllers/app.ts
> +/** The App class initializes the game, sets up generators, creates admin and players, and starts the game. */
https://saritasa.atlassian.net/browse/JC-621
The requirement is that if anyone scores 21 first they will win the game (this is unfair because player plays first will get more chance to win the game), and the requirement says that no need to implement 'stop the game'. There are so many cases that are not right but I think that this requirement's target is just teaching us how to use Observer pattern 😁

2024-07-17 04:20 UTC, kytran-saritasa commented on apps/vanilla/src/pages/black-jack/scripts/controllers/players.ts
> +	private readonly winStatus = new Publisher<WinStatus>();
Yes brother, I had doubts about that problem too. But in the diagram, the player holds his own dice results, so he can cheat. My solution is to give the admin the power to hold all the results of all players, allowing the admin to decide everything. However, in this project, I implemented it as shown in the diagram to avoid any confusion when everyone reviewing my code.

2024-07-17 10:23 UTC, violetta-klintsova commented on apps/vanilla/src/pages/black-jack/scripts/controllers/players.ts
> +class Attender {
I see that you added this class to then extend `Admin` and `Player` from it. I guess something like `User` or `BaseUser` would make a bit more sense here

2024-07-17 10:23 UTC, violetta-klintsova commented on apps/vanilla/src/pages/black-jack/scripts/utils/elements.ts
> + */
You code is documented so well. Great job, keep it up! 👍🏼

2024-07-18 02:21 UTC, kytran-saritasa commented on apps/vanilla/src/global/variables.css
>  	--gap-huge: 80px;
Thank you so much:3, my head always spins around when it comes to naming a variable:)

2024-07-18 02:28 UTC, kytran-saritasa commented on apps/vanilla/src/pages/black-jack/index.html
> +				<button type="button" class="main-button main-button_action font-medium make-a-move">Make a Move</button>
Thanks sister ❤️. When it came to name a button several days ago I felt not comfortable with the name 'makeAMove', now 'makeMove' makes sense:)

2024-07-22 03:24 UTC, andrey-gazzaev approved these changes
Good job, it would be nice if the game could be started over again. 🔥

2024-07-22 03:24 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/black-jack/scripts/types/displayer-types.ts
> +	/** The instance of InitialPlayerDisplayer. */
```suggestion
	/** The instance of {@link InitialPlayerDisplayer}. */
```

2024-07-22 03:24 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/black-jack/styles/base.css
> +	user-select: none;
Why did you remove the ability to select elements? If you take away one opportunity from the user, you must give him an alternative

2024-07-22 03:24 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/black-jack/scripts/views/results-displayers.ts
> +	 * @param infoResultClass - The CSS class used to select the element displaying the sum of dice results.
You have one parameter in the function

2024-07-23 02:36 UTC, kytran-saritasa commented on apps/vanilla/src/pages/black-jack/scripts/types/displayer-types.ts
> +	/** The instance of InitialPlayerDisplayer. */
I will implement the "Start game again" soon, brother 🔥🔥

2024-07-23 02:53 UTC, kytran-saritasa commented on apps/vanilla/src/pages/black-jack/scripts/controllers/app.ts
> +	}
Wow, so 'unsubscribe' can be used for start the game again. I'm gonna implement it soon when I finish the first Angular task 🔥🔥

2024-07-23 03:04 UTC, merged