Feature: JC-657 Anime List Management
saritasa-nest/camp-js-2024-ky-tran pull request #5
Opened 2024-08-11 05:21 UTC by kytran-saritasa

2024-08-12 11:05 UTC, daoduong-saritasa commented on apps/angular/src/app/features/home/anime-table/anime-table.component.html
> +		id="table"
Do we need `id` for table?

2024-08-12 11:10 UTC, daoduong-saritasa commented on apps/angular/src/app/features/home/anime-table/anime-table.component.ts
> +	@Input({ required: true, transform: booleanAttribute })
Do we need `transform` for this?

2024-08-12 11:11 UTC, daoduong-saritasa commented on apps/angular/src/app/features/home/anime-table/anime-table.component.ts
> +	}
Please do not handle error by passing it down to component, consider handling it by piping it wherever the source was called.

2024-08-12 11:13 UTC, daoduong-saritasa commented on apps/angular/src/app/features/home/anime-table/anime-table.component.ts
> +	private readonly filterParamsProvider$ = inject(FILTER_PARAMS_TOKEN);
Declaring private entity before protected for consistency
```suggestion
	private readonly filterParamsProvider$ = inject(FILTER_PARAMS_TOKEN);
	
	/** Convert the list to MatTableDataSource to use MatSort. */
	protected readonly dataSource = new MatTableDataSource<Anime>();
```

2024-08-12 11:16 UTC, daoduong-saritasa commented on apps/angular/src/app/features/home/anime-table/anime-table.component.ts
> +		this.tableEl = this.elementRef.nativeElement.querySelector(`#table`);
Please use [View Queries](https://angular.dev/guide/components/queries#view-queries) for accessing elements

2024-08-12 11:19 UTC, daoduong-saritasa commented on apps/angular/src/app/features/home/anime-table/anime-table.component.ts
> +		this.sortChange.emit(MatSortEventMapper.fromDto({ active: active as MatSortEventFieldsDto, direction }));
Please do not use mapper in UI layer, this will violate abstraction, review [architecture section on wiki](https://wiki.saritasa.rocks/frontend/frameworks/architecture/). You can emit the value and let the domain layer handle the mapping

2024-08-12 11:22 UTC, daoduong-saritasa commented on apps/angular/src/app/features/home/anime-table/anime-table.component.ts
> +		return anime.englishTitle ?? anime.japaneseTitle ?? 'Anime image';
Prefer `japaneseTitle` first

2024-08-12 11:24 UTC, daoduong-saritasa commented on apps/angular/src/app/features/home/home.component.html
> +		/>
This should be placed in table component

2024-08-12 11:27 UTC, daoduong-saritasa commented on apps/angular/src/app/features/home/home.component.ts
> +	protected readonly animeList$ = new BehaviorSubject<Pagination<Anime> | null>(null);
It's weird to have `animeList` as an subject, this way would mean this data is not reliable as it can be `next` with wrong data :). Consider changing it to observable and only handle only one stream of data.

2024-08-12 11:28 UTC, daoduong-saritasa commented on apps/angular/src/app/features/home/home.component.ts
> +	protected readonly error$ = new BehaviorSubject('');
We don't need this, please review `catchError` pipe and handle error for streams there

2024-08-12 11:35 UTC, daoduong-saritasa commented on apps/angular/src/app/features/home/home.component.ts
> +	}
Please review this. Note that the error notification should have it's own service to handle, that way the usage for managing error for observable stream should look sth like this `.pipe(this.notificationService.notifyAppError())`
```suggestion
		protected readonly animeList$: Observable<Pagination<Anime>>;

		public constructor() {
			this.animeList$ = this.filterParamsProvider$
			.pipe(
				tap(filterParams => this.pagePaginator$.next({ pageNumber: filterParams.pageNumber, pageSize: filterParams.pageSize })),
				switchMap(filterParams => this.animeService.getAnimeList(filterParams).pipe(
					toggleExecutionState(this.isLoading$),
					catchError((error: unknown) => throwError(() => {
						const errorMessage = error instanceof Error ? error.message : 'Something went wrong!';
						this.snackBar.openFromComponent(SnackbarComponent, {
							verticalPosition: 'top',
							horizontalPosition: 'right',
							data: { errorMessage },
						});
						return error;
					})),
				)),
				shareReplay({ refCount: true, bufferSize: 1 }),
			)
		}
```

2024-08-12 11:38 UTC, daoduong-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +	public getAnimeList(filterParams: AnimeFilterParams.Combined): Observable<Pagination<Anime>> {
```suggestion
	public getList(filterParams: AnimeFilterParams.Combined): Observable<Pagination<Anime>> {
```

2024-08-12 11:40 UTC, daoduong-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +				catchError((_: unknown) => throwError(() => new Error('Something went wrong. Please try again.'))),
Please do not throw general error. Try to extract the message from the api and display it to UI

2024-08-12 11:44 UTC, daoduong-saritasa commented on libs/core/dtos/anime-type-query-params.dto.ts
> +	Unknown = 'unknown',
It's weird to have this enum dto with normal case

2024-08-12 11:44 UTC, daoduong-saritasa commented on libs/core/dtos/sort-direction-query-params.dto.ts
> +export enum SortDirectionQueryParamsDto {
Do we need this enum?

2024-08-12 11:45 UTC, daoduong-saritasa commented on libs/core/dtos/sort-fields-query-params.dto.ts
> +}
Same here, why do we need this?

2024-08-12 11:46 UTC, daoduong-saritasa commented on libs/core/mappers/mat-sort-event.mapper.ts
> +		if (dto.direction === 'asc') {
We have enum for it, please use.

2024-08-12 11:46 UTC, daoduong-saritasa commented on libs/core/mappers/mat-sort-event.mapper.ts
> +			direction = 'desc';
Same here

2024-08-13 00:21 UTC, kytran-saritasa commented on apps/angular/src/app/features/home/home.component.ts
> +	}
🔥🔥🔥

2024-08-13 02:47 UTC, kytran-saritasa commented on apps/angular/src/app/features/home/anime-table/anime-table.component.ts
> +	@Input({ required: true, transform: booleanAttribute })
Yeah sure we need it, from outside we can pass something like `loading$ | async` and we don't have to take care of the case 'null', transform will handle it to become false value -> TypeScript will happy with this

2024-08-13 04:03 UTC, khoanguyen-saritasa requested changes

2024-08-13 04:03 UTC, khoanguyen-saritasa commented on libs/core/tsconfig.app.json
> +  "include": ["**/*.ts", "../../apps/angular/src/core/mappers/pagination.mapper.ts"]
You can remove this `"../../apps/angular/src/core/mappers/pagination.mapper.ts"`.

2024-08-13 04:03 UTC, khoanguyen-saritasa commented on libs/core/types/non-nullable-fields.ts
> +/** Override-a-property-to-be-non-nullable. */
?

2024-08-13 04:03 UTC, khoanguyen-saritasa commented on libs/core/models/base-filter-params.ts
> +	export type Combined = Paginator & Search;
Missing `readonly`

2024-08-13 04:03 UTC, khoanguyen-saritasa commented on libs/core/models/anime-filter-params.ts
> +}
Readonly ?

2024-08-13 13:59 UTC, kytran-saritasa commented on apps/angular/src/app/app.routes.ts
> +	{ path: 'home', component: HomeComponent },
Hello brother, I am gonna delete lazy loading for all, I use Defer instead.
```
<main class="main">
	@defer {
		<router-outlet />
	} @placeholder {
		<camp-progress-spinner />
	} @error {
		<camp-error-message />
	}
</main>
```
Please check: [Deferrable views](https://angular.dev/guide/defer)

2024-08-13 14:03 UTC, kytran-saritasa commented on apps/angular/src/app/features/home/anime-table/anime-table.component.ts
> +	}
We don't need it actually, I just practiced creating custom transform and didn't understand them thoroughly at that time. I am gonna delete it, thank you.

2024-08-13 14:07 UTC, kytran-saritasa commented on apps/angular/src/app/features/home/anime-table/anime-table.component.ts
> +	}
Without transform
<img width="684" alt="Screenshot 2024-08-13 at 9 07 32 PM" src="https://github.com/user-attachments/assets/8dd6a353-5059-4ede-9fc4-bbcca5ada7b3">

2024-08-13 14:08 UTC, kytran-saritasa commented on apps/angular/src/app/features/home/anime-table/anime-table.component.ts
> +	protected readonly pagePaginator: NonNullableFields<BaseFilterParams.Paginator> | null = null;
Same as above

2024-08-15 08:47 UTC, daoduong-saritasa approved these changes

2024-08-15 08:47 UTC, daoduong-saritasa commented on apps/angular/src/app/features/home/anime-table/anime-table.component.ts
> +	protected set animeList(values: readonly Anime[]) {
It's strange to see a protected `input`, I think they should be public because as the name speaks by itself, an input should be updated from outside the class.

2024-08-15 08:47 UTC, daoduong-saritasa commented on apps/angular/src/app/features/home/anime-table/anime-table.component.ts
> +		return japaneseTitle ?? englishTitle ?? 'Anime image';
Good catch on destructuring params :+1:

2024-08-15 08:47 UTC, daoduong-saritasa commented on apps/angular/src/app/features/home/home.component.ts
> +import { 	BehaviorSubject, Observable, shareReplay, switchMap, tap } from 'rxjs';
Weird indentation

2024-08-15 08:53 UTC, daoduong-saritasa commented
There's a bug on preview, if select all option then select other option, it do nothing. Expected behavior that select all can not be selected with other options, it's one or another, all option is selected then other options will get selected also and when one option deselected, all will be deselected.

https://github.com/user-attachments/assets/3798fcdb-ac3b-4c64-a9c6-0f3df3764e1b

2024-08-22 11:32 UTC, khoanguyen-saritasa commented on apps/angular/src/app/features/home/home.component.ts
> +	}
@kytran-saritasa  This is not resolved yet.

2024-08-22 11:33 UTC, khoanguyen-saritasa commented on apps/angular/src/app/features/home/home.component.ts
> +	}
@kytran-saritasa  This is not resolved yet.

2024-08-22 11:33 UTC, khoanguyen-saritasa approved these changes

2024-08-23 02:53 UTC, kytran-saritasa commented on apps/angular/src/app/features/home/home.component.ts
> +	}
![Screenshot 2024-08-23 at 9 51 37 AM](https://github.com/user-attachments/assets/9c902df5-91c7-4df5-871c-14deebf7a9ed)
I already fixed it bratan, I don't know well how git works but I guess something is not displayed properly.

2024-08-23 03:00 UTC, kytran-saritasa commented on apps/angular/src/app/features/home/anime-table/anime-table.component.ts
> +	protected set animeList(values: readonly Anime[]) {
As I understand, we can use protected here because we have 'transform' property, that means an input is not handled by outside but 'transform' in the component takes care of it before assigning value for the input. So TypeScript is still happy with this.

2024-08-23 04:45 UTC, kytran-saritasa commented
@daoduong-saritasa Hello bratan, I have just updated the filter function as you commented above. Please take a look, thank bratan so much ❤️
The deployed link here: [https://saritasa-nest.github.io/camp-js-2024-ky-tran/pr-preview/pr-5](https://saritasa-nest.github.io/camp-js-2024-ky-tran/pr-preview/pr-5)

2024-08-23 06:09 UTC, daoduong-saritasa approved these changes

2024-08-27 03:08 UTC, merged